accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from .views import RegistrationView, ProfileView, UserPageView


app_name = 'accounts'
urlpatterns = [
    url(r'^register/$', RegistrationView.as_view(), name='register'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', lambda r: logout(r, next_page='/'), name='logout'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/(?P<username>\w+)/$', UserPageView.as_view(), name='user_page'),
]

nospoil/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView


home_page_view = TemplateView.as_view(template_name='home_page.html')

urlpatterns = [
    url(r'^$', home_page_view, name='home_page'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^playoffs/', include('playoffs.urls')),
    url(r'^api/', include('playoffs.urls_rest')),
    url(r'^api-auth/', include('rest_framework.urls')),
]

playoffs/urls.py
from django.conf.urls import url
from .views import index, create, update, detail


app_name = 'playoffs'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^new/$', create, name='create'),
    url(r'^edit/(?P<pk>[0-9]+)/$', update, name='update'),
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/$', detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', detail),
]

accounts/models.py
from __future__ import unicode_literals
from django.db import models

playoffs/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from .helpers import get_grid, slugify


class Playoff(models.Model):
    sport = models.CharField(max_length=32, blank=True)
    title = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    double = models.BooleanField(default=True)  # double or single elimination
    rounds = models.PositiveSmallIntegerField(default=5)
    private = models.BooleanField(default=False)  # only owner can edit
    owner = models.ForeignKey(User, null=True, related_name='playoffs',
                              on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-last_modified']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        if not self.owner:
            self.private = False
        super(Playoff, self).save(*args, **kwargs)

    def get_absolute_url(self):
        kwargs = {'pk': self.pk, 'slug': self.slug}
        return reverse('playoffs:detail', kwargs=kwargs)

    @property
    def grid(self):
        # grid explained in helpers.get_grid function
        values = ('position', 'side_a', 'side_b', 'winner_a', 'youtube_id')
        matches = list(self.matches.order_by('position').values(*values))
        return get_grid(matches, self.rounds, self.double)

    def __unicode__(self):
        return self.title


class Match(models.Model):
    playoff = models.ForeignKey(Playoff, related_name='matches',
                                on_delete=models.CASCADE)
    # position explained in helpers.get_match_positions
    position = models.CharField(max_length=8)
    side_a = models.CharField(max_length=32, blank=True)  # side: team/player
    side_b = models.CharField(max_length=32, blank=True)
    winner_a = models.NullBooleanField()
    youtube_id = models.CharField(max_length=32, blank=True)

    class Meta:
        unique_together = (('playoff', 'position'),)

    def __unicode__(self):
        return '{}: {} - {}'.format(self.position, self.side_a, self.side_b)

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import FormView

from playoffs.models import Playoff


class RegistrationView(FormView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = '/'
    
    def form_valid(self, form):
        name = form.cleaned_data['username']
        password = form.cleaned_data['password1']
        user = User.objects.create_user(name, password=password)
        new_user = authenticate(username=name, password=password)
        login(self.request, new_user)
        return super(RegistrationView, self).form_valid(form)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'registration/profile.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super(ProfileView, self).get_context_data(*args, **kwargs)
        context['playoffs'] = Playoff.objects.filter(owner=self.request.user)
        return context


class UserPageView(DetailView):
    model = User
    context_object_name = 'user'
    template_name = 'accounts/user_page.html'

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')
        obj = get_object_or_404(User, username=username)
        return obj
    
    def get_context_data(self, *args, **kwargs):
        context = super(UserPageView, self).get_context_data(*args, **kwargs)
        context['playoffs'] = Playoff.objects.filter(owner=self.object)
        return context

playoffs/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse

from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Playoff
from .permissions import IsOwnerOrPublicOrReadOnly
from .serializers import PlayoffListSerializer, PlayoffDetailSerializer
from .services import get_empty_grid, inc_playoff_views, update_last_viewed


# ==== Template Views ==== #

def index(request):
    context = {'playoffs': Playoff.objects.all()}
    return TemplateResponse(request, 'playoffs/index.html', context)


def create(request):
    context = {'is_create_view': True}
    return TemplateResponse(request, 'playoffs/form.html', context)


def update(request, pk):
    playoff = get_object_or_404(Playoff, pk=pk)
    if playoff.private and request.user != playoff.owner:
        raise PermissionDenied('You can not edit this playoff')
    context = {'playoff': playoff, 'is_owner': request.user==playoff.owner}
    return TemplateResponse(request, 'playoffs/form.html', context)


def detail(request, pk, slug=None):
    playoff = get_object_or_404(Playoff, pk=pk)
    inc_playoff_views(playoff)
    update_last_viewed(request.session, playoff)
    is_editable = playoff.owner == request.user or not playoff.private
    context = {'playoff': playoff, 'is_editable': is_editable}
    return TemplateResponse(request, 'playoffs/detail.html', context)


# ==== Api Views ==== #

@api_view(['GET'])
def empty_grid(request, format=None):
    return Response(get_empty_grid())


class PlayoffList(generics.ListCreateAPIView):
    queryset = Playoff.objects.all()
    serializer_class = PlayoffListSerializer

    def perform_create(self, serializer):
        if self.request.user.is_authenticated:
            serializer.save(owner=self.request.user)
        else:
            serializer.save()


class PlayoffDetail(generics.RetrieveUpdateAPIView):
    queryset = Playoff.objects.all()
    serializer_class = PlayoffDetailSerializer
    permission_classes = (IsOwnerOrPublicOrReadOnly, )

    def perform_update(self, serializer):
        if self.request.user != serializer.instance.owner:
            # only owner can make playoff private
            serializer.save(private=False)
        else:
            serializer.save()

accounts/templates/accounts/user_page.html
{% extends 'base.html' %}

{% block title %}{{ user }}'s Profile | {{ block.super }}{% endblock %}


{% block content %}
  <h1>Palyoffs by {{ user }}</h1>
  {% if playoffs %}
    <ul>
      {% for playoff in playoffs %}
        <li><a href="{% url 'playoffs:detail' playoff.id playoff.slug %}">{{ playoff.title }}</a> - {{ playoff.sport }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No playoffs so far.</p>
  {% endif %}
{% endblock %}

playoffs/templates/playoffs/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ playoff.title }} | {{ block.super }}{% endblock %}

{% block extra_body %}
  <script type="text/javascript" src="https://unpkg.com/vue/dist/vue.min.js"></script>
  <script type="text/javascript" src="{% static 'playoffs/detail.js' %}"></script>
{% endblock %}


{% block content %}
  <h1 class="text-center">${ playoff.title }</h1>

  <div>
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#winners" aria-controls="winners grid" role="tab" data-toggle="tab">
          <template v-if="playoff.grid.loosers">Winners </template>Grid
        </a>
      </li>
      <li v-if="playoff.grid.loosers" role="presentation">
        <a href="#loosers" aria-controls="Loosers grid" role="tab" data-toggle="tab">Loosers Grid</a>
      </li>
      <li v-if="playoff.grid.final" role="presentation">
        <a href="#final" aria-controls="Grand Final" role="tab" data-toggle="tab">Grand Final</a>
      </li>
      <li role="presentation">
        <a href="#video" aria-controls="video player" role="tab" data-toggle="tab">Video Player</a>
      </li>
    </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="winners">
        <playoff-table is-winners="true" :grid="playoff.grid.winners" @watch="watch"></playoff-table>
      </div>
      <div v-if="playoff.grid.loosers" role="tabpanel" class="tab-pane" id="loosers">
        <playoff-table :grid="playoff.grid.loosers" @watch="watch"></playoff-table>
      </div>
      <div v-if="playoff.grid.final" role="tabpanel" class="tab-pane" id="final">
        <div class="graand-final-wrapper">
          <match-detail :match="playoff.grid.final" @watch="watch"></match-detail>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane" id="video">
        <h3 class="text-center">${ watchTitle }</h3>
        <p class="text-center">NOTE: Controls are turned off because I don't want you to know when the video ends.<br/>
          Use hotkeys for navigation: left/right arrows, J, K, L, and other</p>
        <div class="embed-responsive embed-responsive-16by9">
          <iframe v-if="watchSrc" class="embed-responsive-item" :src="watchSrc"></iframe>
        </div>
      </div>
    </div>
  </div>

  <div class="row created-by">
    <div class="col-xs-6">
      <p>Playoff created by
        {% if playoff.owner %}<a href="{% url 'accounts:user_page' playoff.owner.username %}">{{ playoff.owner }}</a>
        {% else %}anonymous{% endif %}
      </p>
    </div>
    <div class="col-xs-6 text-right">
      {% if is_editable %}
        <p><a href="{% url 'playoffs:update' playoff.pk %}">Edit this playoff</a></p>
      {% endif %}
    </div>
  </div>
{% endblock %}

playoffs/templates/playoffs/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% if is_create_view %}Create{% else %}Edit{% endif %} Playoff | {{ block.super }}{% endblock %}

{% block extra_body %}
  <script type="text/javascript" src="https://unpkg.com/vue/dist/vue.min.js"></script>
  <script type="text/javascript" src="{% static 'playoffs/form.js' %}"></script>
{% endblock %}


{% block content %}
  <h1 class="text-center">{% if is_create_view %}Create{% else %}Edit{% endif %} Playoff</h1>

  <form id="playoff-form" class="form-horizontal" @submit.prevent="postData">
    <div class="form-group">
      <label class="sr-only" for="title">Playoff Title</label>
      <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
        <input v-model="playoff.title" id="title" type="text" maxlength="64" required
               class="form-control input-lg" placeholder="Playoff Title">
      </div>
    </div>

    <div class="form-group">
      <label class="sr-only" for="sport">Kind of Sport</label>
      <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
        <input v-model="playoff.sport" id="sport" type="text" maxlength="32"
               class="form-control" placeholder="Kind of Sport">
      </div>
    </div>

    {% if is_create_view and request.user.is_authenticated or is_owner %}
      <div class="form-group">
        <label class="sr-only" for="private">Private</label>
        <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
          <input v-model="playoff.private" id="private" type="checkbox" class="hidden">
          <checkbox-switcher @tick="playoff.private=true" @untick="playoff.private=false"
                             ticked-btn="Private" ticked-ph="only you can edit"
                             unticked-btn="Public" unticked-ph="enyone can edit"
                             :is-ticked="playoff.private"></checkbox-switcher>
        </div>
      </div>
    {% endif %}

    <div v-if="playoff.rounds" class="form-group">
      <label class="sr-only" for="rounds">Rounds Number</label>
      <div class="col-sm-3 col-sm-offset-2 col-md-2 col-md-offset-3">
        <select v-model="playoff.rounds" class="form-control" id="rounds">
          <option v-for="option in roundOptions" :value="option.value">${ option.text }</option>
        </select>
      </div>
      <label class="sr-only" for="double">Double Elimination</label>
      <div class="col-sm-5 col-md-4">
        <input v-model="playoff.double" id="double" type="checkbox" class="hidden">
        <checkbox-switcher @tick="playoff.double=true" @untick="setSingleElimination"
                           :is-ticked="playoff.double" ticked-btn="Double" ticked-ph="elimination"
                           unticked-btn="Single" unticked-ph="elimination"></checkbox-switcher>
      </div>
    </div>

    <div>
      <ul id="tablist" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
          <a href="#winners" aria-controls="winners grid" role="tab" data-toggle="tab">
            <template v-if="showLoosersGrid">Winners </template>Grid
          </a>
        </li>
        <template v-if="showLoosersGrid">
          <li role="presentation">
            <a href="#loosers" aria-controls="Loosers grid" role="tab" data-toggle="tab">Loosers Grid</a>
          </li>
          <li role="presentation">
            <a href="#final" aria-controls="Grand Final" role="tab" data-toggle="tab">Grand Final</a>
          </li>
        </template>
      </ul>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="winners">
          <playoff-table is-winners="true" :grid="playoff.grid.winners" @update="updateWinners"
            :rounds="{% if is_create_view %}playoff.rounds{% else %}playoff.grid.winners.length{% endif %}">
          </playoff-table>
        </div>
        <div role="tabpanel" class="tab-pane" id="loosers" v-if="playoff.grid.loosers">
          <playoff-table :grid="playoff.grid.loosers" @update="updateLoosers"
            :rounds="{% if is_create_view %}playoff.rounds{% else %}playoff.grid.winners.length{% endif %}">    
          </playoff-table>
        </div>
        <div role="tabpanel" class="tab-pane" id="final" v-if="playoff.grid.final">
          <match-form v-bind:match="playoff.grid.final" @update="updateFinal"></match-form>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-5 col-sm-2">
        <button type="submit" class="btn btn-primary btn-lg btn-block">
          {% if is_create_view %}Save{% else %}Update{% endif %}
        </button>
      </div>
    </div>

  </form>
{% endblock %}

playoffs/templates/playoffs/index.html
{% extends 'base.html' %}

{% block title %}All Playoffs | {{ block.super }}{% endblock %}


{% block content %}
  <h1>All Palyoffs</h1>
  <ul>
    {% for playoff in playoffs %}
      <li><a href="{% url 'playoffs:detail' playoff.id playoff.slug %}">{{ playoff.title }}</a> - {{ playoff.sport }}</li>
    {% endfor %}
  </ul>
{% endblock %}

playoffs/templates/playoffs/playoff_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ playoff.title }} | {{ block.super }}{% endblock %}

{% block extra_body %}
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  <script type="text/javascript" src="{% static 'playoffs/playoff-viewing.js' %}"></script>
{% endblock %}


{% block content %}
  <h1 class="text-center">{{ playoff.title }}</h1>

  <div>
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#winners" aria-controls="winners grid" role="tab" data-toggle="tab">
          {% if playoff.double %}Winners {% endif %}Grid
        </a>
      </li>
      {% if playoff.double %}
        <li role="presentation">
          <a href="#loosers" aria-controls="Loosers grid" role="tab" data-toggle="tab">Loosers Grid</a>
        </li>
        <li role="presentation">
          <a href="#final" aria-controls="Grand Final" role="tab" data-toggle="tab">Grand Final</a>
        </li>
      {% endif %}
      <li role="presentation">
        <a href="#video" aria-controls="video player" role="tab" data-toggle="tab">Video Player</a>
      </li>
    </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="winners">
        {% include 'playoffs/playoff_table.html' with rounds=grid.winners %}
      </div>
      {% if playoff.double %}
        <div role="tabpanel" class="tab-pane" id="loosers">
          {% include 'playoffs/playoff_table.html' with rounds=grid.loosers %}
        </div>
        <div role="tabpanel" class="tab-pane" id="final">
          <div class="graand-final-wrapper">
            {% include 'playoffs/match_detail.html' with match=grid.grand_final %}
          </div>
        </div>
      {% endif %}

      <div role="tabpanel" class="tab-pane" id="video">
        <h3 class="text-center">Select match to watch from grid</h3>
        <p class="text-center">NOTE: Controls are turned off because I don't want you to know when the video ends.<br/>
          Use hotkeys for navigation: left/right arrows, J, K, L, and other</p>
        <div class="embed-responsive embed-responsive-16by9">
          <iframe id="ytplayer" class="embed-responsive-item"></iframe>
        </div>
      </div>
    </div>
  </div>

  <div class="row created-by">
    <div class="col-xs-6">
      <p>Playoff created by
        {% if playoff.owner %}<a href="{% url 'accounts:user_page' playoff.owner.username %}">{{ playoff.owner }}</a>
        {% else %}anonymous{% endif %}
      </p>
    </div>
    <div class="col-xs-6 text-right">
      {% if editable %}<a href="{% url 'playoffs:update' playoff.pk %}">Edit this playoff</a>{% endif %}
    </div>
  </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="NoSpoil. Enjoy playoffs without spoilers">
    <title>{% block title %}NoSpoil{% endblock %}</title>

    <link rel="icon" href="{% static 'favicon.ico' %}">
    {# <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block extra_head %}{% endblock %}
  </head>
  <body>
    {% include 'header.html' %}
    <div id="content" class="container">
      {% block content %}{% endblock %}
    </div>
    {% include 'footer.html' %}

    {# <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script> #}
    {# <script src="{% static 'js/bootstrap.min.js' %}"></script> #}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block extra_body %}{% endblock %}
  </body>
</html>

templates/footer.html
<footer class="footer">
  <div class="container">
    <p>Made by a simple guy who thinks this is realy usefull.
       <a href="mailto:nospoil.guy@gmail.com">contact me</a>
    </p>
    <p>Just kidding. I'm looking for a job and made this as portfolio project.</p>
    <p><a href="https://github.com/RomanOsadchuk/nospoil">Project source</a>. Created with
      <a href="https://www.djangoproject.com/">django</a>,
      <a href="https://vuejs.org/">vue.js</a> and
      <a href="http://getbootstrap.com/">bootstrap</a>.
    </p>
  </div>
</footer>

templates/header.html
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">NoSpoil</a>
    </div>

    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        {% if 'last_viewed' in request.session %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Last Viewed <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              {% for playoff in request.session.last_viewed %}
                <li><a href="{% url 'playoffs:detail' playoff.pk playoff.slug %}">{{ playoff.title }}</a></li>
              {% endfor %}
            </ul>
          </li>
        {% endif %}
        <li><a href="{% url 'playoffs:index' %}">All Playoffs</a></li>
        <li><a href="{% url 'playoffs:create' %}">Add Playoff</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
          <li><a href="{% url 'accounts:profile' %}">My Profile</a></li>
          <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <li><a href="{% url 'accounts:register' %}">Register</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/home_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="home-page">
    <h1>NoSpoil <small>Enjoy playoffs without spoilers</small></h1>
    <hr class="promo-divider"/>
    <div class="row promo">
      <div class="col-md-5">
        <img class="img-responsive center-block" src="{% static 'img/promo-grid.png' %}" alt="Grid that spoils">
      </div>
      <div class="col-md-7">
        <h2>Next round participants are hidden</h2>
        <p class="lead">Often when you want to watch some awesome quarter-final match, you see semi-final participants by accidant. (Like in the picture on the left) This info spoils you the winner. But here at NoSpoil all next rounds participants are hidden.</p>
      </div>
    </div>
    <hr class="promo-divider"/>
    <div class="row promo">
      <div class="col-md-7">
        <h2>No time bars</h2>
        <p class="lead">Also when you see only 15 mins left until the end of the video you can guess the winner. You can deduce that your favourite player will not comeback to that game. That sucks. But here at NoSpoil time bars are off.</p>
      </div>
      <div class="col-md-5">
        <img class="img-responsive center-block" src="{% static 'img/promo-time-bar.png' %}" alt="Time bar that spoils">
      </div>
    </div>
    <hr class="promo-divider"/>
    <h1 class="text-right"><small>Enjoy playoffs without spoilers</small> NoSpoil</h1>
  </div>
{% endblock %}